version: 0.2
env:
  variables:
    SECRET_NAME:  # Name of the secret in Secrets Manager


phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - sudo apt install -y jq
      - echo  Insalling Dependencies....
      - apt-get update
      # - aws secretsmanager get-secret-value --secret-id $json-object --query 'DEV' --output text | jq -r '.docusignPrivateKey' > key.key
      # - apt-get install openssl -y

  build:
    commands:
      - echo Build started on `date`
      # - aws secretsmanager get-secret-value --secret-id $json_object --query 'DEV' --output text | jq -r '.privateKey' > key.key

      # - touch env
      # - echo $json_object >> private.key
      # - empId=$(echo $json_object | python3 -c "import sys, json; print(json.load(sys.stdin)['DEV'])")
      # - echo $empId >> key.key
      # - chmod 777 key.key
      - empId=$(node -e \ "let argv=process.argv; let Obj=argv.slice(1,argv.length).join(''); console.log(JSON.parse(Obj)['data'][0]['empId']);" \ $json_object )
      # - openssl rsa -in key.key -out domain-rsa.key
      - chmod 600 key.key
      # - openssl rsa -in key.key -out domain-rsa.key -text -noout
 

  post_build:
    commands:
      - echo Build completed on `date`
      - openssl rsa -in docusign.key -out domain-docusign.key

 

artifacts:
  files:
    - '**/*'
  discard-paths: false
