version: 0.2
env:
  exported-variables:
    - TEST

phases:
  install:
    commands:
      - echo  Insalling Dependencies....
      - apt-get update
  build:
    commands:
      - echo Build started on `date`
      - touch env
      - echo "TEST='${TEST}'" >> env
      

  post_build:
    commands:
      - echo Build completed on `date`

 

artifacts:
  files:
    - '**/*'
  discard-paths: false
